### ISSUE TITLE
Provide comparison to https://github.com/alfert/propcheck

### ISSUE THREAD

**Issue by turion** [whatyouhide/stream_data#113]
For me, being an Elixir newcomer, it is hard to decide whether to use https://github.com/alfert/propcheck or this project for property based testing. Can you explain somewhere in the docs:

* what the design differences are
* what the relevant features are that help me decide between one or the other
* possibly why the projects aren't merged

**Comment by bryanhuntesl** [comment]
Propcheck is a wrapper on top of [PropEr](https://github.com/proper-testing/proper).

PropEr supports [stateful testing](https://www.propertesting.com/book_stateful_properties.html) - (functionality for verifying state machines). 

If you need to verify state machines you will probably need to use PropEr or [Quickcheck](http://www.quviq.com/products/erlang-quickcheck/) (commercial product)

You might want to take a look at Fred's [book](https://pragprog.com/book/fhproper/property-based-testing-with-proper-erlang-and-elixir) for more context.

**Comment by bryanhuntesl** [comment]
The projects proably aren't merged because PropEr uses a GPL license, and this code is Apache 2.

**Comment by bryanhuntesl** [comment]
Maybe create a PR to add to FAQ and close this issue?

**Comment by turion** [comment]
Good idea. I feel like I don't understand enough still for a good comparison.

**Comment by whatyouhide** [comment]
Added this info in the README. Thanks everyone.
