### ISSUE TITLE
StreamData.string(:assigned)

### ISSUE THREAD

**Issue by isaac-rstor** [whatyouhide/stream_data#120]
Would anyone else be interested in string stream that only generates *assigned* unicode codepoints?  This is coming up since I'm fuzzing some MacOS filenames, and APFS only allows assigned(unicode9.0) codepoints.  If there's interest, I could probably do a PR request by next week.

**Comment by isaac-rstor** [comment]
the tricky part is that this might involve some codegen from some unicode consortium files, which can get complicated.

**Comment by whatyouhide** [comment]
@isaac-rstor if it involves storing Unicode files in the stream_data repo and parsing them at compile-time, I would say that it's out of the scope of this library and that maybe a separate library would be a better option. Is that what you meant with "codegen from some Unicode consortium files"?

**Comment by isaac-rstor** [comment]
Exactly.  Ok - I'll go ahead and make a separate library!  Thanks.
