### ISSUE TITLE
`check` can't be used without generators

### ISSUE THREAD

**Issue by mbramson** [whatyouhide/stream_data#123]
I believe that there's a use case where one would want to check a property that does not require generating any random values. This could be the case for some nullary function that depends on some random process, like generating a hash.

Currently, the `check` macro doesn't allow this.

If used like so:

```
propery "always returns a 32 byte binary" do
  check all do
    assert <<hash::binary-size(32)>> = generate_hash()
  end
end
```

the following error is seen, because this function does not exist.
```
== Compilation error in file test/secrets_test.exs ==
** (FunctionClauseError) no function clause matching in ExUnitProperties.check/2
    (stream_data) expanding macro: ExUnitProperties.check/2
    test/hash_test.exs:9: Hashing."property generate_hash/0 always returns a 32 byte binary"/1
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/kernel/parallel_compiler.ex:209: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

I could see why this would happen, although that would be a pretty decent API for this. If I try passing an empty list of generators like so:

```
propery "always returns a 32 byte binary" do
  check all [] do
    assert <<hash::binary-size(32)>> = generate_hash()
  end
end
```

This runs up against an internal assertion:

```
== Compilation error in file test/secrets_test.exs ==
** (FunctionClauseError) no function clause matching in ExUnitProperties.assert_first_clause_is_generator/1

    The following arguments were given to ExUnitProperties.assert_first_clause_is_generator/1:

        # 1
        []

    Attempted function clauses (showing 2 out of 2):

        defp assert_first_clause_is_generator([{:<-, _, [_, _]} | _])
        defp assert_first_clause_is_generator([clause | _])

    (stream_data) lib/ex_unit_properties.ex:247: ExUnitProperties.assert_first_clause_is_generator/1
    (stream_data) lib/ex_unit_properties.ex:238: ExUnitProperties.compile/2
    (stream_data) expanding macro: ExUnitProperties.gen/2
    test/hash_test.exs:9: Hashing."property generate_hash/0 always returns a 32 byte binary"/1
    (stream_data) expanding macro: ExUnitProperties.check/2
    test/hash_test.exs:9: Hashing."property generate_hash/0 always returns a 32 byte binary"/1
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/kernel/parallel_compiler.ex:209: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

I could just generate an integer or something and throw it away, but that seems wasteful. Would be better to express in the test, that there are no values to be generated.

What do you think?

**Comment by whatyouhide** [comment]
Hey @mbramson, thanks for the report. I don't think you want to use stream_data for your use case:

```elixir
for _ <- 1..100 do
  assert <<hash::binary-size(32)>> = generate_hash()
end
```

I think this is a much better and clearer way of doing it. Using stream_data without generators has really no benefit because you can't use shrinking anywhere. If you want to use `check all` so that the number of runs is the same as other tests, you can just use the range `1..Application.get_env(:stream_data, :max_runs)` in the comprehension above.

Hopefully that makes sense!

**Comment by mbramson** [comment]
Yep, that sounds super reasonable and obvious :). Thank you!
