### ISSUE TITLE
Missing generators for (Date)(Time)s and MapSets.

### ISSUE THREAD

**Issue by Qqwy** [whatyouhide/stream_data#126]
Some very common datatypes, most notably the Date/DateTime/Time/NaiveDateTime structs, do not yet have generators.

Also, a generator combinator function to generate MapSets from would be very welcome. Generaitng a MapSet from a list is possible, but not so nice because duplicate list elements will disappear, so a dedicated generator will definitely be faster.

**Comment by whatyouhide** [comment]
@Qqwy regarding MapSets, today there's `uniq_list_of/2` so a MapSet generator is a matter of `map(uniq_list_of(...), &MapSet.new/1)`. Not sure that a function that just does this is worth adding to the library.

As for the date and time generators, I'm not sure how to make those flexible enough to be general and be in the library. Ideas on the API?

**Comment by Qqwy** [comment]
:thinking: 
Because we want them to be deterministic, they should not be based on actual clock times.
A naive implementation would be to generate them from integers, but this would not come up with much interesting edge cases, and probably not shrink well either.
The one thing that probably should be configurable is a range for the timestamps to be generated, because while it is possible to add this as a filter, you will probably filter away too much if you do.

Edge cases that the generators should address (in this order of 'complexness', i.e. shrink the other way):

- timestamps in the 'near' future. (2020 - 2050)
- timestamps in the 'near' past, after the Posix epoch. (2019 - 1970)
- leap days.
- leap seconds.
- timestamps in the further future
- timestamps in the further past

and the other kind of complexness, which should be interspersed with above stack, would be:

- year/month/day
- year/month/day/hour
- year/month/day/hour/minute
- year/month/day/hour/minute/seconds
- year/month/day/hour/minute/seconds/microseconds


(Where all non-mentioned parts would be e.g. '0' if the (Naive)(Date)(Time)-type supports them).

Since Elixir on its own only ships with `Calendar.ISO` and `Calendar.UTCOnlyTimeZoneDatabase` I do not think that `stream_data` should contain generators for other calendars / timezones.


---

Regarding MapSets: Besides the fact that `uniq_list_of` uses a MapSet under the hood to construct its unique list (which would be an argument in favour of the hypothetical situation `uniq_list_of = map(map_set(), &MapSet.to_list/1)`) the main reason to add it is to make it as simple as possibl to start using the library in your code. 
Your argument can be used against many of the existing functions, like `keyword_of`, `nonempty`, `byte`, `binary`, `improper_list_of`. A user of the library could have written them as well. Yes, some of them are used in implementations of other, less trivial generators. However, I think that adding their abstraction really helps to allow users care less about writing generators and more about having generators to compose.
I think that a MapSet generator is a clean and simple building block that would be very helpful for people, because otherwise many people will end up writing the same code.

**Comment by whatyouhide** [comment]
I added `mapset_of/2` in deb4ca3281dc2cebc363575ae37ddee46289e507.

**Comment by whatyouhide** [comment]
> Regarding MapSets: Besides the fact that uniq_list_of uses a MapSet under the hood to construct its unique list (which would be an argument in favour of the hypothetical situation uniq_list_of = map(map_set(), &MapSet.to_list/1))

`uniq_list_of/2` has a `:uniq_fun` option to customize what makes an item unique, so `mapset_of/1` *has* to be built on top of `uniq_list_of/2`.

**Comment by Qqwy** [comment]
> > Regarding MapSets: Besides the fact that uniq_list_of uses a MapSet under the hood to construct its unique list (which would be an argument in favour of the hypothetical situation uniq_list_of = map(map_set(), &MapSet.to_list/1))
> 
> `uniq_list_of/2` has a `:uniq_fun` option to customize what makes an item unique, so `mapset_of/1` _has_ to be built on top of `uniq_list_of/2`.

I am not entirely sure what you mean: In the current implementation of `mapset_of/1` all options except `:max_tries` are discarded, making it irrelevant wether you use `uniq_list_of/2` or another function that might be more optimized for a MapSet specifically.

**Comment by whatyouhide** [comment]
> In the current implementation of mapset_of/1 all options except :max_tries are discarded, making it irrelevant wether you use uniq_list_of/2 or another function that might be more optimized for a MapSet specifically.

What I’m saying is that if I didn't reuse the `uniq_list_of/1` function, I would have to have implemented a lot of crossover between the two functions. I can implement `mapset_of/2` on top of `uniq_list_of/2` very easily, but not the other way around. Anyways, this is not really relevant to the issue, I just wanted to mention this to avoid confusion.

**Comment by whatyouhide** [comment]
Closing this and moving the datetimes discussion to #129.
