### ISSUE TITLE
`atom(:operator)` documented but not implemented

### ISSUE THREAD

**Issue by Qqwy** [whatyouhide/stream_data#127]
See https://github.com/whatyouhide/stream_data/blob/v0.4.3/lib/stream_data.ex#L1766.

When trying to use this in practice, you receive the following stacktrace:

```elixir
  3) property atom/1 and unsafe_atom/1 Works on strings (Confy.ParsersTest)
     test/confy/parsers_test.exs:127
     ** (FunctionClauseError) no function clause matching in StreamData.atom/1

     The following arguments were given to StreamData.atom/1:
     
         # 1
         :operator
     
     Attempted function clauses (showing 2 out of 2):
     
         def atom(:alphanumeric)
         def atom(:alias)

```

This is probably related to #115 .

**Comment by whatyouhide** [comment]
Ah, good catch @Qqwy! I decided to avoid `atom(:operator)` (as mentioned in #115) but forgot that I had already added docs for it. Fixed now.
