### ISSUE TITLE
Generators for Date, Time, and DateTime values

### ISSUE THREAD

**Issue by whatyouhide** [whatyouhide/stream_data#129]

**Comment by Qqwy** [comment]
It's a good call to split my earlier issue into two. :+1: 

Just to make sure it does not get lost, you can see my earlier thoughts as to what functionality Date/Time/DateTime generator(s) might require [here](https://github.com/whatyouhide/stream_data/issues/126#issuecomment-486051843).

**Comment by whatyouhide** [comment]
After a couple of years, I still think that having a good date generator is worth it but I'm afraid of putting it into the library because I think the requirements for what dates should look like vary a lot between applications. For now, unless someone wants to give this a shot, I'm closing this!

**Comment by Qqwy** [comment]
While I agree that requirements for dates vary between applications, I think that there is a large majority of libraries and applications for which it is good enough to be able to generate:

- Any (future and past) (date)(time);
- Any future (date)(time);
- Any past (date)(time).

In some cases, it might make sense to round them to the nearest second/minute/hour/day, or to rescale them to ensure a larger range. Both of these things can be done using pre-existing tooling outside of the (date)(time) generators themselves (e.g. the tools of the Elixir standard library and/or Timex, and the use of `StreamData.scale/2`).

---

I am willing to give this a shot. Expect a PR in the next couple of days. :-)
