### ISSUE TITLE
Missing generators for functions

### ISSUE THREAD

**Issue by 21it** [whatyouhide/stream_data#138]
Maybe I searched in wrong place, but I can't find generators for functions. For now I just used other library PropCheck (PropEr) to implement [this](https://github.com/tkachuk-labs/wonderland/blob/67ee5645492126c921f18a99486ce66ab335ad1a/test/prop_test.exs#L141-L142) kind of tests. But maybe it make sense to have function generators in StreamData?

**Comment by Qqwy** [comment]
The theory to create generators for functions is not actually that difficult.

A possible implementation which the TypeCheck library uses (wrapping StreamData), [can be found here](https://github.com/Qqwy/elixir-type_check/blob/master/lib/type_check/builtin/function.ex#L167-L203).

The larger difficulty is to decide on how people indicate a particular function type. I'm not sure whether there is a nice way for StreamData to do this by itself.

**Comment by whatyouhide** [comment]
I don't plan on implementing this in stream_data for now. I'd be happy if someone gave it a try and implemented this _on top_ of stream_data and, if it goes well, we can think about backporting it back in here 🙃

**Comment by Qqwy** [comment]
> I'd be happy if someone gave it a try and implemented this on top of stream_data and, if it goes well, we can think about backporting it back in here upside_down_face

This is exactly what I've done in TypeCheck (and linked to above). As mentioned, the main difficulty will be to describe what exact type (i.e. what input types and return type) the function is supposed to have in a way that is consistent with the rest of StreamData's DSL.
