### ISSUE TITLE
Generator for existing atoms only

### ISSUE THREAD

**Issue by tanguilp** [whatyouhide/stream_data#141]
The idea is to enable working with libraries using `String.to_existing_atom/1`

**Comment by whatyouhide** [comment]
@tanguilp thanks for the issue! However, this sounds a bit vague. What atoms should stream_data generate out of the existing ones? How would shrinking work? Can you expand on how you think this would look like from a usage perspective? Thanks!

**Comment by Qqwy** [comment]
@tanguilp I think an alternative is to:

1. generate arbitrary strings using `stream_data`
2. Inside the forall clause, call `String.to_atom/1` on the generated string to make sure it exists.
3. Now you can pass the string to a location that uses `String.to_existing_atom` without errors being raised on strings that happen not to exist as atoms.

The inverse case (only generate strings that do not exist as atoms) can be tested by rejecting all generated strings for which `String.to_existing_atom` does _not_ raise.

**Comment by tanguilp** [comment]
@Qqwy solutions sounds like the right way to go! Closing.
