### ISSUE TITLE
StreamData.integer/1 does not handle ranges with steps correctly

### ISSUE THREAD

**Issue by Qqwy** [whatyouhide/stream_data#158]
Given

```elixir
generator = StreamData.integer(2..8//2)
```

When calling 

```elixir
generator |> Enum.take(1_000) |> MapSet.new
```

the expected output is

```elixir
#MapSet<[2, 4, 6, 8]>
```
(i.e. the same as calling `MapSet.new(2..8//2)`)

but instead we get

```elixir
#MapSet<[2, 3, 4, 5, 6, 7, 8]>
```

It seems StreamData is not taking the `step` field (introduced in Elixir 1.12) into account.

**Comment by Qqwy** [comment]
I'd be willing to contribute a PR to fix this, by the way :slightly_smiling_face:

**Comment by whatyouhide** [comment]
@Qqwy yep, definitely not taking steps into account yet. Please do send a PR! 💟
