### ISSUE TITLE
Revisit string API

### ISSUE THREAD

**Issue by whatyouhide** [whatyouhide/stream_data#17]
Right now we have a few functions that are specific to string generation:

* `StreamData.binary/0`
* `StreamData.alphanumeric_string/0`
* `StreamData.ascii_string/0`
* `StreamData.string_from_chars/1`

I think we can devise a better API. I think it's nice to have `binary/0` and something else that generates "strings" because we make the same distinction in Elixir with `t:binary/0` and `t:String.t/0`. However `ascii_`, `alphanumeric_`, show that this trend may introduce many functions over the course of StreamData's life.

An alternative (originally suggested by @josevalim) could be to have only one function, `string/1`, whose argument can be

* `:alphanumeric`
* `:ascii`
* `:printable` (maybe?)
* an enumerable of characters to be used, for example `?a..?f` or `Enum.concat([?0..?9, ?a..?f])` or `[?=, ?/, ?-]`

Thoughts?

**Comment by whatyouhide** [comment]
Closed in 2cb4f5f.

**Comment by sobolevn** [comment]
I think that there some predefined sets are still missing and can be added. 
`:printable` was a good idea. I can also think of use cases with `:unicode` set.

**Comment by whatyouhide** [comment]
So in order to do this, we need to yet again change the API for `string/1`. Right now it takes a "mode" (`:ascii`, ...) or a list of codepoints. However `0x10000..0x10FFFF` for example is pretty big and we access it by index in order to find the next codepoint. Long story short it's slow as hell and not feasible.

Proposed new API: a list of codepoint ranges or codepoint lists:

```elixir
string([0x10000..0x10FFFF, [?_]])
```

Thoughts? \cc @josevalim

**Comment by josevalim** [comment]
Make it a range or a list of ranges and codepoints. I think a list of
codepoints and forcing a list of ranges is too much, no?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
