### ISSUE TITLE
Simple generator for random/constant/unshrinkable things

### ISSUE THREAD

**Issue by zachdaniel** [whatyouhide/stream_data#172]
I can't seem to find a way to make a simple generator for something like `&Ecto.UUID.generate/0`.  Per #38, `bind/2` works I think because the inner generator is recreated each time, so my best guess on implementing that generator is currently

```elixir
# Just picking any generator here
StreamData.integer()
|> StreamData.bind(fn _i -> StreamData.constant(Ecto.UUID.generate()) end)
|> StreamData.unshrinkable()
```

It seems strange to have to build off of another generator for no good reason there.

```elixir
StreamData.constant(Ecto.UUID.generate()) |> Enum.take(10)
```
This doesn't work, as naturally the list simply repeats the generated uuid.

**Comment by whatyouhide** [comment]
@zachdaniel yep, that's a valid point!

The easiest way is probably something like this:

```elixir
map(boolean(), fn _ → Ecto.UUID.generate() end)
```

which is very similar to what you show above. I’m open to having something like `StreamData.from_stream/1` though? It would be an **unshrinkable** generator that takes any stream and converts it to a StreamData generator. With that, you could implement the UUID as:

```elixir
&Ecto.UUID.generate/0
|> Stream.repeatedly()
|> StreamData.from_stream()
```

Thoughts?

**Comment by whatyouhide** [comment]
@zachdaniel I’m ok to start with `StreamData.repeatedly/1`. Wanna go for a PR? 🙃

**Comment by zachdaniel** [comment]
Absolutely :)
