### ISSUE TITLE
Release 1.0 missing in Hex

### ISSUE THREAD

**Issue by vrcca** [whatyouhide/stream_data#193]
Hi @whatyouhide, I noticed that there's a [1.0 release in the CHANGELOG](https://github.com/whatyouhide/stream_data/blob/main/CHANGELOG.md#v100), but I cannot find it in hex? 👀

https://hex.pm/packages/stream_data/1.0.0

Thanks!

**Comment by whatyouhide** [comment]
Done! ✔️
