### ISSUE TITLE
Refine generator names

### ISSUE THREAD

**Issue by whatyouhide** [whatyouhide/stream_data#23]
- [x] `non_empty/1` - should probably be `nonempty/1` given we already have types such as `nonempty_list/1` and similar in Erlang. @lexmag is responsible for this PR :P (he delivered! 💪)
- [x] `int/0,1` - should these be `integer/0,1`? \cc @josevalim
- [x] `no_shrink/1` - maybe `unshrinkable/1`

**Comment by lexmag** [comment]
Worth mentioning that we already have `nonempty_improper_list_of`. PR is coming. :bowtie:

**Comment by keathley** [comment]
I like the idea of using `integer()` over `int()` because it stays consistent with typespecs. I'm not sure thats a goal but its nice to have one less thing to remember. If you think thats a good change I'd be happy to make a PR.

**Comment by josevalim** [comment]
:+1: for `integer()`. That's the "official" term we use, so we should stick with it.
