### ISSUE TITLE
Improve the list_of/1 generator and its friends

### ISSUE THREAD

**Issue by whatyouhide** [whatyouhide/stream_data#26]
Today `list_of/1` only decides the size of the resulting list based on the generation size. I propose that we make `list_of/2` into `list_of/2` which takes options like `:length` (for a specific length) or `:max_length`/`:min_length`:

```elixir
list_of(integer(), max_length: 10)

# this would be common I think because I often wrote nonempty(list_of(integer())
list_of(integer(), min_length: 1) 

list_of(integer, length: 4) |> map(&:inet.ntoa/1)
```

I can think of two APIs:

  * `:length`, `:max_length`, and `:min_length` (all integers)
  * a single `:length` option that can be `int` (exact length), `min..max`, `{:min, min}`, `{:max, max}`

We would have to add the same options to `uniq_list_of/1` for now, and maybe in the future to `map_of/1` as well.

What do you think?

**Comment by josevalim** [comment]
I personally prefer `length: int | min..max`.

**Comment by whatyouhide** [comment]
@josevalim what about when you want to specify a minimum or maximum length only? `{:min, min}`/`{:max, max}`? I can't think of anything good :|

**Comment by josevalim** [comment]
@whatyouhide specify a large integer as max? :P

**Comment by whatyouhide** [comment]
@josevalim I don't think it's too much about how you achieve the min/max length but mostly about expressing that the list should have a min length or a max length only.

**Comment by josevalim** [comment]
`length: int | min..max, min_length: int, max_length: int`?

**Comment by whatyouhide** [comment]
@josevalim sounds good to me 👍

**Comment by whatyouhide** [comment]
Done in a19441e91f9dd67befdbb29f9dbec65f8dde1d6f and #27.
