### ISSUE TITLE
Length-related options for StreamData.string/1

### ISSUE THREAD

**Issue by LostKobrakai** [whatyouhide/stream_data#29]
I just tried a binary example with length options from the docs and only later noticed, that I want to have strings and not raw binaries. I was a bit surprised to see that the length options are not available for the string() generator as well. Using filters quickly results in `StreamData.FilterTooNarrowError` errors.

**Comment by whatyouhide** [comment]
Makes sense to have length options in `string/1` as well. @josevalim 👍 from your side?

I am afraid that we need a better solution for specifying length because we're duplicating these options in many "collection" generators but that might make perfect sense.

**Comment by LostKobrakai** [comment]
Until you know how to rework it I've added #30

**Comment by whatyouhide** [comment]
Closed by #30.
