### ISSUE TITLE
Suggestion for pos_integer generator

### ISSUE THREAD

**Issue by keathley** [whatyouhide/stream_data#33]
What would you think about adding a generator for positive integers? This use case has come up in a number of the generators that I've written so far. Guarding against negative integers with something like `counter <- integer(), counter > 0` tends to induce errors because it skips too many generations. The solution we've been using so far is to use ranges with an arbitrarily high positive number. Having something like `pos_integer` seems like it would be more intention revealing.

If this is something that you think might be useful I'd be more then happy to work on it. Let me know what you think or if there's an alternative solution for this problem that I haven't considered.

**Comment by josevalim** [comment]
:+1: because we can easily get `negative_integer()` with a map and we can get from 0 by concatenating two of them.

**Comment by whatyouhide** [comment]
Should we call this `pos_integer/0`, or `positive_integer/0`?

**Comment by josevalim** [comment]
I prefer `positive_integer` honestly. But we would need to search Elixir and see if we use the `pos_` notation anywhere besides dialyzer. /cc @lexmag

**Comment by whatyouhide** [comment]
We only use `pos_` in typespecs in Elixir so I went with `positive_integer/0` in 07d6c34f688e09448ee15a868e1fce1a15c19ed1.
