### ISSUE TITLE
Question about `StreamData.gen all ...`

### ISSUE THREAD

**Issue by ckampfe** [whatyouhide/stream_data#34]
Hey there, I've started using StreamData already to do some random data generation and am definitely enjoying it.

I'm curious as to the syntax and function of the `all` in `StreamData.gen all $CLAUSES`. I haven't been able to find anything about the `all` term anywhere in the code or docs. I see it defined here as https://github.com/whatyouhide/stream_data/blob/master/lib/stream_data.ex#L1743. Is there a reason the `all` surrounded by spaces is necessary? What differentiates the two terms of `gen all` from `check_all`, which is one?

Thank you!

**Comment by josevalim** [comment]
`gen all` is a macro and it requires the `all` bit in order to handle multiple arguments. The `check_all` is just a regular function without multiple args.

**Comment by whatyouhide** [comment]
As @josevalim said :). Gonna close this now, if you have ideas on how to improve documentation on this, please submit a PR or comment here/reopen this issue. 💟

**Comment by ckampfe** [comment]
thank you!
