### ISSUE TITLE
Figure out how options will be passed to check_all

### ISSUE THREAD

**Issue by josevalim** [whatyouhide/stream_data#4]

**Comment by whatyouhide** [comment]
We will start with `check/3` accepting options alongside generators (similarly to how `for` accepts `into`):

```elixir
check all bin <- binary(),
           max_runs: 100 do
  assert is_binary(bin)
end
```

We will have a global configuration for the `stream_data` application alongside this (similarly to ExUnit configuration), so you can do

```elixir
PropertyTest.configure(max_runs: 100)
```

in `test_helper.exs` and all `check/3`s will default to that unless specified (like `receive_timeout` works in ExUnit).

**Comment by whatyouhide** [comment]
Implemented in https://github.com/whatyouhide/stream_data/commit/73019bb0306ee7d2288a3cec483e3c57ac846330 and https://github.com/whatyouhide/stream_data/commit/e32ea0be1c6dd7da6848a8ad7249b40939900273.
