### ISSUE TITLE
Provide more combinators

### ISSUE THREAD

**Issue by alfert** [whatyouhide/stream_data#49]
I would like to see more combinators to create more complex data, in particular
* to create recursive data structures like arbitrary algebraic types 
* a reducer to create data depending on the already generated elements

Background: 

I tried to port the examples from `propcheck` and `PropEr` to `StreamData`, but failed to generate data for the tree example with the following structure:

    @type tree :: :leaf | {:node, integer, tree, tree}

In `propcheck`, you can write

    def tree(), do:
      one_of([:leaf, {:node, integer(), lazy(tree()), lazy(tree())])

where `lazy` simply encapsulates the following expression in a `fn -> expression end`. 

The reducers could be a nice solution for generating command sequences to support symbolic state machines for property testing of stateful systems. Here we start with an initial state and generate commands depending on the current state and producing a new state. A `reduce` or `unfold`  function could be a solution for that problem. 

If this goes along your development direction of `StreamData`, I can work on PRs for that.

**Comment by josevalim** [comment]
Nice @alfert! @whatyouhide is there any way to build such trees today?

**Comment by whatyouhide** [comment]
The tree can be generated by using `StreamData.tree/2`:

```elixir
def my_tree() do
  tree(:leaf, fn leaf_data ->
    {:node, integer(), leaf_data, leaf_data}
  end)
end
```

which can be used as:

```elixir
iex> Enum.at(resize(g, 20), 1)
{
  :node,
  -1,
  {
    :node,
    2,
    {:node, 3, :leaf, :leaf},
    {:node, 0, :leaf, {:node, 0, :leaf, :leaf}}
  },
  {:node, 1, :leaf, :leaf}
}
```

I am not sure about the stateful generators. @josevalim thoughts on that?

**Comment by alfert** [comment]
Thanks @whatyouhide, this was really enlightening. I misunderstood the documentation such that the first parameter of `tree` is the generator for entire node, since it is called again in `subtree_fun`. 

After reporting this issue, I finally managed to write a recursive generator without introducing a `lazy` combinator. I assume that `lazy` is not needed in `propcheck` as well.  The recursive generator for the trees above requires a size argument to abort the recursion and looks like this: 

```elixir
def my_tree(g), do: tree_gen(g) 
defp tree_gen(g), do: sized(fn size -> tree_gen(size, g) end)
defp tree_gen(0, _g), do: :leaf
defp tree_gen(size, g), do:
   frequency([
      {1, tree_gen(0, g)},
      {9, ({:node, g, 
        resize(tree_gen(g), div(size, 2)),
        resize(tree_gen(g), div(size, 2))})}
   ])
```
With the `frequency` I control the size of the tree, or better, which kind of nodes are generated more often. If I understand the implementation of `tree()` correctly, than the frequency between leafs and internal nodes is fixed by 1:2. So it depends on the requirements if `tree()` is an appropriate solution and I assume that it is ok most of the time.

**Comment by whatyouhide** [comment]
@alfert yes the generator you wrote works without `tree/2` or `lazy/1` but it's harder to understand in my opinion than `tree/2`. 

This issue asked about tree generators and stateful generators so I'm gonna close it so we avoid mixing discussions. If you want to talk about stateful generators, please open up another issue. 

Also, since it seems like you found the documentation for `tree/2` a bit confusing, could you open up a PR to improve it? I would love for the documentation to be as clear as possible so if you didn't find it super clear I would consider it a bug on our side :).

**Comment by alfert** [comment]
Ok, I will do both.
