### ISSUE TITLE
Introduce StreamData.string_from_codepoint_data/2

### ISSUE THREAD

**Issue by whatyouhide** [whatyouhide/stream_data#53]
This function would be the foundation for the current `StreamData.string/2`. It would have this signature

```elixir
@spec string_from_codepoint_data(StreamData.t(char()), keyword()) :: StreamData.t(String.t())
```

so that it would take a generator responsible for generating codepoints (and a list of options, same as `string/2`) and return a string built by generating the codepoints with the codepoint generator. So for example to generate strings of digits you could do

```elixir
string_from_codepoint_data(integer(?0..?9))
```

Of course you'd be able to write the above with `string([?0..?9])` which is better IMO, but you'd also have the chance to write strings with more complex character distributions (so that for example you can generate strings where Japanese characters are more common or whatever), which is not possible today.

I'd like to hear thoughts. Oh and a small note: the name is definitely to revisit, `string_from_codepoint_data` sucks :) And another note, if you're wondering why we can't accept a generator in `string/2` directly: we don't know what a generator is. For now we know it's either a tuple, an atom, or a `%StreamData{}` struct but that might chance in the future.

\cc @josevalim

**Comment by josevalim** [comment]
@whatyouhide couldn't we allow a range or a list of ranges as argument to string instead?

**Comment by whatyouhide** [comment]
@josevalim we do allow `Range.t() | [Range.t() | char()]` in `string/1` but that doesn't allow you to customize for example the frequency of each character. Does that make it clearer?

**Comment by josevalim** [comment]
@whatyouhide I see but I am not sure if this approach is actually sound for generating other languages. Especially because those likely do not work at the codepoint level.

**Comment by whatyouhide** [comment]
@josevalim languages were just an example, you may want to implement say a password generator which distributes letters in a particular way or something like that.
