### ISSUE TITLE
"Attempts" in error message should count number of test runs until first error

### ISSUE THREAD

**Issue by ericmj** [whatyouhide/stream_data#59]
It seems today it also counts the number of shrinking attempts it did which is less useful to the user.

Another option is to show the generated value it failed on after N attempts and also show the shrunk value and how nodes were visited when shrinking.

**Comment by whatyouhide** [comment]
@ericmj so the way it works is that right now "attempts" only reports the *shrinking* attempts, not the test runs. Is the test runs number really useful? What changes if it was the 2nd or the 87th test run? 🤔 

> Another option is to show the generated value it failed on after N attempts and also show the shrunk value

We had this initially but since our properties are not booleans but actual rich assert-ful tests, we can get a different error when shrinking than the original one. So we are only showing the smallest error you get. Does it make sense? Suggestions to improve this are welcome of course.

**Comment by ericmj** [comment]
> so the way it works is that right now "attempts" only reports the shrinking attempts, not the test runs. Is the test runs number really useful? What changes if it was the 2nd or the 87th test run? 🤔

Let me turn it around and ask why showing the number of shrinking attempts is useful?

For me the number of successful test runs before first failure is interesting because it shows me if an edge case was hit or if there is something fundamentally wrong with my code. If the 87th run fails I know that my code works for most input but it failed on some edge case so it gives me an indication of where to start looking for the bug. The bug is probably not in the hot path but rather in one of the parts of the code that is not hit for most inputs.

Maybe I am missing something but for me showing number of shrinking attempts gives me no information. What does 10 shrinks or 100 shrinks mean? Do I need to understand the internals 
of the shrinking algorithm for this to be useful?

**Comment by whatyouhide** [comment]
Okay fair enough. It could make sense to say that it failed at the nth run. The number of shrinking attempts can reveal how well your generators shrink: if you have a good result after a few shrinks it's going well. But I agree it might not be that useful. What about the other question? :P

**Comment by ericmj** [comment]
> The number of shrinking attempts can reveal how well your generators shrink: if you have a good result after a few shrinks it's going well. But I agree it might not be that useful.

Can I define my own shrinkers? Otherwise it's just showing how well algorithms I can't affect performs :).

> We had this initially but since our properties are not booleans but actual rich assert-ful tests, we can get a different error when shrinking than the original one. So we are only showing the smallest error you get. Does it make sense? Suggestions to improve this are welcome of course.

This does make sense, both errors can be shown but I think it's more useful to only show the shrunk error since it should be more minimal.
