### ISSUE TITLE
Ability to generate an any() type

### ISSUE THREAD

**Issue by Adzz** [whatyouhide/stream_data#66]
First of all this lib is awesome, thank you!

I am attempting to test a generated list, but it's not important what is inside the list. In fact it's important that we test all kinds of lists - lists with any type of data, and any combination of any kind of data.

If we could have an `any()` type that randomly generated an elixir primitive, we could write something that perhaps approached this possibility. For example you could then say `list_of(StreamData.any())` and `map_of(StreamData.any())`.

Is this at all possible, or is my thinking off here?

Thanks!

**Comment by whatyouhide** [comment]
Hey @Adzz, thanks for the kind words! We have this exact functionality under the [`term/0` generator](https://hexdocs.pm/stream_data/0.4.0/StreamData.html#term/0) :).

**Comment by Adzz** [comment]
Oh my days, how did I miss that! Thanks!
