### ISSUE TITLE
Allow for max_run_time as well as max_runs

### ISSUE THREAD

**Issue by devonestes** [whatyouhide/stream_data#69]
We were discussing property testing a bit last night at our local Elixir meetup here in Berlin, and someone brought up the idea of allowing for a `max_run_time` option as well as `max_runs` to help give a more human-understandable expectation for how long a given property test might run. We thought this might be especially helpful in CI.

As to an implementation, I figure it wouldn't be super hard since this is a very similar feature compared to how we know how long to run benchmarks in Benchee. I'd be happy to help with adding this if you think this is a nice feature to add.

**Comment by whatyouhide** [comment]
Hey @devonestes, yeah this is a nice feature to have. Most property-based testing libraries have this. I agree it would be nice so I am 👍 on going ahead with it.

**Comment by devonestes** [comment]
Cool. How do you think `max_run_time` and `max_runs` should interact? I can think of two ways that we might handle things:

1) We stop at whichever happens first, `max_runs` or `max_run_time`.
2) We emit a warning or raise an exception telling the user that they should use either `max_runs` or `max_run_time` but not both together.

My preference is for number 2 so it's totally clear to the user what's happening, but I can see a valid argument for both, so I'm happy to implement whichever your prefer.

**Comment by josevalim** [comment]
My preference is number 1 because it provides a feature. Number 2 would be good if the behaviour of specifying both could be confusing but I think the whichever happens first is quite reasonable.

**Comment by whatyouhide** [comment]
I agree, number 1 seems like a sensible approach. :)

**Comment by michalmuskala** [comment]
Is there a way to pass those from CLI? For example `mix test --max-runs 1000` or similar.

**Comment by whatyouhide** [comment]
@michalmuskala not yet :)
