### ISSUE TITLE
Is it expected that I have to add :stream_data to extra_applications...

### ISSUE THREAD

**Issue by pragdave** [whatyouhide/stream_data#73]
...when running tests? If I don't, I get

~~~
     test/stats_property_test.exs:11
     ** (ArgumentError) could not fetch application environment :initial_size for appl
ication :stream_data because the application was not loaded/started. If your applicati
on depends on :stream_data at runtime, make sure to load/start it or list it under :ex
tra_applications in your mix.exs file                                                
     code: check all l <- list_of(integer()) do
~~~

Couldn't the config values be defaulted in the code so that this isn't necessary?

Cheers

Dave

**Comment by axelson** [comment]
I don't believe that it should be necessary to add `:stream_data` to `extra_applications`. Do you have a repo that exhibits the error anywhere?

**Comment by josevalim** [comment]
If you are using `:extra_applications` and not the `:applications` key then it should not be necessary as Mix will handle it for you.

However if you use `:applications`, then you need to start it either manually in your test_helper.exs or by adding it to `:applications` under the test environment.
