### ISSUE TITLE
Strange filter behavior

### ISSUE THREAD

**Issue by akrejczinger** [whatyouhide/stream_data#75]
I have this generator:
 ```elixir
  def time(hour_range \\ 0..23, minute_range \\ 0..59, second_range \\ 0..59) do
    gen all hours <- integer(hour_range),
            minutes <- integer(minute_range),
            seconds <- integer(second_range) do

      {:ok, new_time} = Time.new(hours, minutes, seconds)
      new_time
    end
  end
```

I use it like this:
```elixir
      check all start_time <- time() |> filter(&(&1 > ~T[01:00:00]), 100) do
      ...
```

I got an error when running my test:
```
     ** (StreamData.FilterTooNarrowError) too many consecutive elements (25 elements in this case) were filtered out.
      The last element to be filtered out was: ~T[03:37:08]. To avoid this:
      ...
```

I see two problems here:
- The last generated value ~T[03:37:08] is above the given limit ~T[01:00:00], so the filter should not have discarded it.
- I specifically passed in **100** to the filter function to make failures less likely, yet only 25 elements were tried.

I also saw similar failures in code which doesn't even include filters, so maybe the issue is with the error reporting (#60).

**Comment by michalmuskala** [comment]
Structs can't be compared with `>`. The `>` operator does structural and not semantic comparison.

There's a `Time.compare/2` function for semantic comparison of time structs.

**Comment by whatyouhide** [comment]
Hey @akrejczinger, what @michalmuskala said is correct, you can't use `>` to compare time structs (or structs in general) in a meaningful way.

Regarding using `filter(..., 100)` and getting the "25 elements tried" message is something I can't reproduce:

```
iex> StreamData.filter(StreamData.positive_integer(), &(&1 < 0), 100) |> Enum.take(1)
** (StreamData.FilterTooNarrowError) too many consecutive elements (100 elements in this case) were filtered out.
 The last element to be filtered out was: 1.
```

If you find a way to reproduce this, please open up a separate issue explaining how to reproduce. Thanks for reporting this! 💟
