### ISSUE TITLE
fixed_map/1 doesn't work with empty lists and maps

### ISSUE THREAD

**Issue by aaronrenner** [whatyouhide/stream_data#86]
I'm running into an issue where `fixed_map/1` doesn't work with an empty list or empty map. Here's a failing test:

``` elixir
  test "fixed_map/1 accepts empty lists and maps" do
    data_with_map = %{}
    data_with_keyword = []

    Enum.each([data_with_map, data_with_keyword], fn data ->
      check all map <- data do
        assert %{} == map
      end
    end)
  end
```

and here's the failure:

```
  1) test fixed_map/1 accepts empty lists and maps (StreamDataTest)
     test/stream_data_test.exs:431
     ** (ArgumentError) expected a generator, which can be a %StreamData{} struct, an atom, or a tuple with generators in it, but got: %{}
     code: Enum.each([data_with_map, data_with_keyword], fn data ->
     stacktrace:
       (stream_data) lib/stream_data.ex:228: StreamData.bind_filter/5
       (stream_data) lib/stream_data.ex:348: anonymous fn/5 in StreamData.bind_filter/3
       (stream_data) lib/stream_data.ex:201: StreamData.check_all/7
       test/stream_data_test.exs:436: anonymous fn/1 in StreamDataTest."test fixed_map/1 accepts empty lists and maps"/1
       (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
       (elixir) lib/enum.ex:675: Enum.each/2
       test/stream_data_test.exs:435: (test)
```

It seems like a fixed_map when called with an empty map/list should return an empty map.

**Comment by whatyouhide** [comment]
I am not sure the best way about this is to support empty list/map. Maybe we should leave that case for `constant/1`, but maybe supporting it is the sensible thing to do. Thoughts @josevalim?

**Comment by josevalim** [comment]
If I would define a “property” for this function, I would expect it to just
work with empty maps. And then just emit empty maps too.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by whatyouhide** [comment]
Wait, I had read the issue wrong. I can't see the bug in your code @aaronrenner, it's behaving correctly: you're trying to get maps out of `%{}` but `%{}` is not a generator (nor is `[]`), so it's erroring out. You're not calling `fixed_map/1` anywhere in your code.

In case you meant that you want maps to be generators like tuples/atoms are, for now we're only sticking with tuples/atoms because for examples we wouldn't know if to mimic `optional_map/1` or `fixed_map/1` if we just used maps as generators.

**Comment by aaronrenner** [comment]
🤦‍♂️ You're right, I forgot the `fixed_map` call.
