### ISSUE TITLE
Figure out what options check/3 and check_all/3 should accept

### ISSUE THREAD

**Issue by whatyouhide** [whatyouhide/stream_data#9]
`StreamData.check_all/3` accepts:

  * `initial_seed`
  * `initial_size` (default `1`) - initial generation size
  * `total_runs` - number of tests to run
  * `max_shrinking_steps` - shrinks this number of steps max

`PropertyTest.check/3` accepts:

  * `initial_size` (as above)
  * `total_runs` (as above)
  * `max_shrinking_steps` (as above)

What does everybody think about the names of these options? Do you feel the need for more options?

For example, there's no option to limit the generation size so if you have `total_runs: 1000`, the generation size will go up to 1000 which is not great. In `StreamData.check_all/3` you can limit by using `scale(data, &min(&1, 200))` as the first argument but there's no way to do this on `PropertyTest.check/3`, so maybe there a `max_size` option makes sense.

**Comment by josevalim** [comment]
Looks good to me. I am also ok on `max_size`, even if we have scaled, having an option that doesn't require us to wrap bound generator is not a bad idea.

**Comment by whatyouhide** [comment]
Added an option `max_generation_size` only to `PropertyTest.check/3` for now (easy to do it with `StreamData.scale/2` in `StreamData.check_all/3` and renamed `:total_runs` to `:max_runs`. Closing this for now.
