### ISSUE TITLE
Displaying number of runs for a given test

### ISSUE THREAD

**Issue by justanotherdot** [whatyouhide/stream_data#95]
It would be nice to have the total number of runs for each property displayed after each test e.g. 

`QuickCheck`:
```
+++ OK, passed 100 tests.
```

[`hedgehog`](https://github.com/hedgehogqa/haskell-hedgehog):
```
━━━ Test.Example ━━━
  ✓ prop_reverse passed 100 tests.
  ✓ 1 succeeded.
```

Would there be an interest in having something similar? In a maze of property tests I find this extra information invaluable when there's a need to tweak things based on the characteristics of each test.

And thanks for the fantastic library! 🎉

**Comment by whatyouhide** [comment]
This is tricky to do in a nice way that integrates well with ExUnit. What do you have in mind for a full ExUnit output of `mix test` that includes this information?

**Comment by justanotherdot** [comment]
Ah, so ExUnit's main test mode would more be for a summary of the whole suite, is that right? 

I'm happy to give a crack at a PR if it's possible to do it with `--trace` or is that tricky as well?

**Comment by josevalim** [comment]
I don't think there is something we can do for now anyway before we merge stream data into Elixir.

**Comment by justanotherdot** [comment]
I can bring this up when that occurs, so I'll close this for now so it's not lingering around. Thanks for the input!
